### ISSUE TITLE
用户在未登录情况下建议 回复框做一个判断 未登录就显示登录连接

### ISSUE THREAD

**Issue by Yakumo-Yukari** [coloz/clz-forum-frontend#1]
![1](https://user-images.githubusercontent.com/12076232/124351450-f7dc1700-dc2c-11eb-936d-9599bbf082dc.png)
![2](https://user-images.githubusercontent.com/12076232/124351454-f90d4400-dc2c-11eb-938d-068a2fec666b.png)

好像编辑器图标也没显示  未登录还是能使用编辑器  并且点击发布也为提示用户登录或者跳转到登录也没

**Comment by coloz** [comment]
震惊于居然有人用，三天打鱼两天晒网的项目

**Comment by Yakumo-Yukari** [comment]
> 震惊于居然有人用，三天打鱼两天晒网的项目

233333
